PLAN DE COMIDAS SEMANAL
==================================================
Generado: 18/07/2025 17:17:33


🗓️ LUNES--------------------------------------------------  Al despertar    | Pan tostado con fresas  Batido          | Batido de pera y manzana con almendras y avena.  Almuerzo        | Ensalada de pepino y zanahoria con fajitas de pollo y nuez con tortillas.  Comida          | Guisado de lentejas con zanahoria, champiñones y apio. Acompañado de una ensalada de lechuga con trozos de queso y nueces. Naranja de postre  Colación        | Palomitas naturales hechas a calor con limón y chilito.  Cena            | Pan tostado con pera y queso panela.

🗓️ MARTES--------------------------------------------------  Al despertar    | Avena cocida con manzana en trozos.  Batido          | Batido de pera y manzana con almendras y avena.  Almuerzo        | Ensalada de garbanzo, calabaza y pepino con nueces. Y de postre pan tostado con fresas.  Comida          | 90gr de carne de res con esparragos, brocoli y champiñones con tortillas. De postre una pera con avellanas.  Colación        | Jícama con limón y cacahuates  Cena            | Tacos de atun y de postre fresas

🗓️ MIÉRCOLES--------------------------------------------------  Al despertar    | Pera picada con amaranto  Batido          | Batido de fresa con nueces y linaza.  Almuerzo        | Huevo con jamón y tocino acompañado de guayaba.  Comida          | Carne molida con calabaza, arroz y pimientos, y semillas de calabaza. Una naranja.  Colación        | Jicama con limón y cacahuates  Cena            | Quesadillas y una manzana.

🗓️ JUEVES--------------------------------------------------  Al despertar    | Avena cocida con manzana en trozos.  Batido          | Batido de fresa con amaranto y nuez.  Almuerzo        | Bowl: 125g de yogurt (1 tarrito) + 1 cdita de linaza, chía, semillas de calabaza, avena, nuez picada, arándanos  Comida          | Lentejas guisadas con arroz y champiñones con calabazitas. De postre una pera con nueces.  Colación        | Zanahorias con limón  Cena            | Pan tostado con fresas y rollitos de jamón.

🗓️ VIERNES--------------------------------------------------  Al despertar    | Pan tostado con manzana rebanada  Batido          | Batido de manzana con chía y avena.  Almuerzo        | Bowl: 125g de yogurt (1 tarrito) + 1 cúlta de linaza, chia, semillas de calabaza, avena, nuez picada, arándanos  Comida          | Caldo de pollo con sus verduras y tortillas. Agua de limón con chía  Colación        | Zanahoria y apio con limón y sal.  Cena            | 2 tacos de queso panela con nopales.

🗓️ SÁBADO--------------------------------------------------  Al despertar    | Avena cocida con manzana en trozos.  Batido          | Batido de manzana con chía y avena.  Almuerzo        | Huevos revueltos con bistec de res acompañado de tortillas. Como postre manzana en trozos con linaza  Comida          | Puntas de res con pico de gallo y agua de limon.  Colación        | Pepino con limón y semillas de girasol  Cena            | Quesadilla y guayaba

🗓️ DOMINGO--------------------------------------------------  Al despertar    | Un tazón de durazno con nuez en trozos  Batido          | Batido de manzana con chía y avena.  Almuerzo        | Avena cocida, manzana picada y nuez. Acompañados de dos huevos revueltos.  Comida          | 90gr de arrachera con esparragos, brocoli y champiñones con tortillas. De postre una pera con avellanas.  Colación        | Una taza de pepitas con limón y chile.  Cena            | Pan tostado con queso fresco y durazno
